main: us.ajg0702.antixray.Main
name: ${pluginName}
author: ajgeiss0702, thowan-codes
api-version: 1.21
description: ${description}
version: ${version}
softdepend: [Factions, WorldGuard]

folia-supported: true

commands:
  ajantixray:
    aliases: [xr, aax, ax, ajax]
    description: Main command for ajAntiXray
    usage: /<command>
  ajecho:
    description: Echo back the args you put
    usage: /ajecho
permissions:
  ajaxr.notify:
    description: Players with this permission will recieve notifications when someone is being suspicious.
    default: op
  ajaxr.exempt:
    description: Players with this permission will not set off notifications
    default: op
