blocks:
- DIAMOND_ORE:15
- EMERALD_ORE:5
- LAPIS_ORE:20
- QUARTZ_ORE:90
- REDSTONE_ORE:40
- GOLD_ORE:30
- IRON_ORE:90

block-debug: false

commands-to-execute:
- 'ajecho &c{PLAYER} mined {COUNT} {ORE}s in the past {DELAY} minutes [remove/change this command in the config]'

blocks-in-last-minutes: 5

factions-integration: true

notify-sound: NONE